### ISSUE TITLE
Cash match question

### ISSUE THREAD

**Issue by msolucky** [innovatesac/2018-rails-guidelines#18]
I have a question about the cash match. I am assessing three different accelerator proposals focusing on three different subject areas (energy, agriculture, health). I would like to submit 3 different proposals for $50,000 each. Would this require a cash match if all three are awarded?

**Comment by Aubree-J** [comment]
We will not accept more than one application from a single organization. You may choose to submit your proposal for the strongest proposal or put together a proposal which includes all 3 accelerators (or some combination of the 3). If your proposal is for $100,000 or more, it will require the cash match.

**Comment by msolucky** [comment]
Thank you!
